import sys
import os

# Add parent directory to sys.path so imports work smoothly
sys.path.insert(0, os.path.dirname(__file__))

from colab_client import ColabModelClient
from config import COLAB_API_URL

def test():
    print("=" * 65)
    print(" 🧪 TESTING CONNECTION TO GOOGLE COLAB MODEL")
    print(f" Target Endpoint: {COLAB_API_URL}")
    print("=" * 65)

    if "your-ngrok-subdomain" in COLAB_API_URL or not COLAB_API_URL.startswith("http"):
        print("\n❌ Error: COLAB_API_URL is not set.")
        print("Please edit 'colab_integration/config.py' and insert the ngrok URL")
        print("generated by your Colab notebook (e.g. https://xxxx.ngrok-free.app).\n")
        return

    client = ColabModelClient()

    # Step 1: Health Check
    print("\n[Step 1/3] Pinging Colab server...")
    try:
        health_resp = client.check_health()
        print(f"✅ Success! Colab server is online: {health_resp}")
    except Exception as e:
        print(f"❌ Failed to reach Colab server: {e}")
        return

    # Step 2: Push Single Sample
    print("\n[Step 2/3] Sending sample data to model endpoint (/predict)...")
    sample_payload = {
        "candidate_id": "user_101",
        "role": "Data Scientist",
        "extracted_skills": ["Python", "SQL", "Machine Learning"]
    }
    try:
        prediction = client.push_and_get_data(sample_payload)
        print("✅ Success! Model returned prediction:")
        print(prediction)
    except Exception as e:
        print(f"❌ Failed getting prediction: {e}")
        return

    # Step 3: Batch Predict
    print("\n[Step 3/3] Sending batch data (/batch_predict)...")
    batch_payload = [
        {"role": "Frontend Developer", "skills": ["React", "TypeScript"]},
        {"role": "Data Analyst", "skills": ["Excel", "Power BI", "SQL"]}
    ]
    try:
        batch_res = client.batch_predict(batch_payload)
        print(f"✅ Batch success! Received {batch_res.get('count', 0)} predictions.")
    except Exception as e:
        print(f"⚠️ Batch predict test error: {e}")

    print("\n🎉 ALL TESTS PASSED! Your local app is fully connected to Colab.\n")

if __name__ == "__main__":
    test()
